openapi: "3.1.0"
info:
  version: 1.0.0
  title: Lishogi.org API reference
  contact:
    name: "Lishogi.org API"
    url: "https://lishogi.org/api"
    email: "contact@lishogi.org"
  x-logo:
    url: https://lishogi.org/assets/piece/king-logo.svg
    backgroundColor: #ffffff
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  description: |
    # Introduction
    Welcome to the reference for the Lishogi API! Lishogi is a free/libre,
    open-source draughts server powered by volunteers and donations.
    - Get help by email at [contact@lishogi.org](mailto:contact@lishogi.org).
    - [Contribute to this documentation on Github](https://github.com/lishogi-org/api).
    - Check out [lishogi widgets to embed in your website](https://lishogi.org/developers).

    ## Endpoint
    All requests go to `https://lishogi.org` (unless otherwise specified).

    ## Rate limiting
    All requests are rate limited using various strategies,
    to ensure the API remains responsive for everyone.
    Only make one request at a time.
    If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),
    please wait a full minute before resuming API usage.

    ## Streaming with ND-JSON
    Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.

    Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses.

    ## Authentication
    ### Personal Access Token
    Personal API access tokens allow you to quickly interact with Lishogi API without going through an OAuth flow.
    - [Generate a personal access token](https://lishogi.org/account/oauth/token)
    - `curl https://lishogi.org/api/account -H "Authorization: Bearer {token}"`
servers:
  - url: https://lishogi.org
tags:
- name: Account
  description: |
    Read and write account informations and preferences.
    https://lishogi.org/account/preferences/game-display
- name: Users
  description: |
    Access registered users on Lishogi.
    https://lishogi.org/player
- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lishogi.
    https://lishogi.org/games
- name: Teams
  description: |
    Access and manage Lishogi teams and their members.
    https://lishogi.org/team
- name: Bot
  description: "Play on Lishogi as a bot. Allows engine play.\n
  \ Only works with [Bot accounts](#operation/botAccountUpgrade).\n\n\
  \n### Features\n\
  \ - [Stream incoming draughts moves](#operation/botGameStream)\n\
  \ - [Play draughts moves](#operation/botGameMove)\n\
  \ - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games\n\
  \ - Engine assistance is allowed\n\
  \n### Restrictions\n\
  \ - Bots can only play challenge games: lobby and tournaments are off-limits\n\
  \n### Integrations\n\
  \ None as of yet. Let us know if you have made a working bot client!"
- name: Challenges
  description: |
    Send and receive challenges to play.
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lishogi.
    [Official Arena tournaments](https://lishogi.org/tournament) are maintained by Lishogi,
    but you can [create your own Arena tournaments](https://lishogi.org/tournament/new) as well.
- name: Simuls
  description: |
    Access simuls played on Lishogi.
    https://lishogi.org/simul
- name: Studies
  description: |
    Access Lishogi studies.
    https://lishogi.org/study
- name: OAuth
  description: |
    Requests taking advantage of OAuth authentication.
    https://lishogi.org/account/oauth/app
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lishogi and playing games.
      tags:
        - Users
      security:
        - None: []
  /player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the top 10 players for each speed and variant.

        See https://lishogi.org/player.
  /player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See https://lishogi.org/player/top/200/bullet.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security:
        - None: []
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security:
        - None: []
      description: |
        Get up to 300 users by their IDs. Users are returned in the order same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public informations about the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - https://lishogi.org/account/preferences/game-display
        - https://github.com/roepstoep/lishogi/blob/master/modules/pref/src/main/Pref.scala
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - https://lishogi.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - https://lishogi.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:write"]
  /game/export/{gameId}:
    get:
      operationId: gamePdn
      summary: Export one game
      description: |
        Download one game in either PDN or JSON format.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - None: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in PDN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long (thousands of games).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 10 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 20 games per second
          - Authenticated, downloading your own games: 50 games per second
      tags:
        - Games
        - OAuth
      security:
        - None: []
        - OAuth2: []
  /games/export/_ids:
    post:
      operationId: gamesExportIds
      summary: Export games by IDs
      description: |
        Download games by IDs in PDN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream games of users
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        Maximum number of users: 300.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security:
        - None: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
        - OAuth
      security:
        - OAuth2: []
  /tv/feed:
    get:
      operationId: tvFeed
      summary: Stream current TV game
      description: |
        Stream positions and moves of the current [TV game](https://lishogi.org/tv) in [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lishogi.org/tv/feed`.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lishogi tournament schedule](https://lishogi.org/tournament).
      tags:
        - "Arena tournaments"
      security:
        - None: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on https://lishogi.org/tournament/new.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teambBattleByTeam` argument.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about an Arena tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security: []
    post:
      operationId: apiTournamentUpdate
      summary: Update an Arena tournament
      description: |
        Update an Arena tournament.

        Ongoing tournaments can no longer be updated.

        Can be used to update a team battle.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}/terminate:
    post:
      operationId: apiTournamentTerminate
      summary: Terminate an Arena tournament
      description: |
        Terminate an Arena tournament
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/team-battle/{id}:
    post:
      operationId: apiTournamentTeamBattlePost
      summary: Update a team battle
      description: |
        Set the teams and number of leaders of a team battle.
        To update the other attributes of a team battle, use the [tournament update endpoint](#operation/apiTournamentUpdate).
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in PDN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.

        Games are sorted by reverse chronological order (most recent first)
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of an Arena tournament
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /study/{studyId}/{chapterId}.pdn:
    get:
      operationId: studyChapterPdn
      summary: Export one study chapter
      description: |
        Download one study chapter in PDN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /study/{studyId}.pdn:
    get:
      operationId: studyChapterPdn
      summary: Export all chapters
      description: |
        Download all chapters of a study in PDN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      tags:
        - Simuls
      security:
        - None: []
  /api/simul/{id}/games:
    get:
      operationId: gamesBySimul
      summary: Export games of a simul
      description: |
        Download games of a simul in PDN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.
      tags:
        - Simuls
      security:
        - None: []
  /api/team/{teamId}:
    get:
      operationId: teamShow
      summary: Get a single team
      description: Infos about a team
      tags:
        - Teams
      security: []
  /api/team/all:
    get:
      operationId: teamAll
      summary: Get popular teams
      description: |
        Paginator of the most popular teams.
      tags:
        - Teams
      security: []
  /api/team/of/{username}:
    get:
      operationId: teamOfUsername
      summary: Teams of a player
      description: |
        All the teams a player is a member of.
      tags:
        - Teams
      security: []
  /api/team/search:
    get:
      operationId: teamSearch
      summary: Search teams
      description: |
        Paginator of team search results for a keyword.
      tags:
        - Teams
      security: []
  /api/team/{teamId}/users:
    get:
      operationId: teamIdUsers
      summary: Get members of a team
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).
        OAuth is only required if the list of members is private.

        Members are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Users
        - Teams
      security:
        - OAuth2: ["team:read"]
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team join policy requires a confirmation but the
        `message` parameter is not given, then the call fails with
        `403 Forbidden`.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - https://lishogi.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - https://lishogi.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must own the team.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
  /streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security:
        - None: []
          SameOrigin: []
  /api/crosstable/{user1}/{user2}:
    get:
      operationId: apiCrosstable
      summary: Get crosstable
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/following:
    get:
      operationId: apiUserFollowing
      summary: Get users followed by a user
      description: |
        Users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Relations
      security:
        - None: []
  /api/user/{username}/followers:
    get:
      operationId: apiUserFollowers
      summary: Get users who follow a user
      description: |
        Users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Relations
      security:
        - None: []
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lishogi user in real time as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\n
      \ Each line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameStart` Start of a game\n
      \ - `challenge` A player sends you a challenge\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Bot
        - Challenges
      security:
        - OAuth2: ["challenge:read", "bot:play"]
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lishogi player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
  /api/challenge/external/{username}:
    post:
      operationId: challengeExternal
      summary: Create an external challenge
      description: |
        Create a challenge between any two players. The targeted players get the choice to join when they visit the challenge url. If both players have joined the game starts.
        
        Optionally a starting date/time can be specified. The challenge page shows a countdown until the specified date/time is reached. Only then do the players get the option to join.

        Players don't get notified when you create an external challenge for them. The only way to find the challenge after it is created is by visiting the url that is returned in the Json.
      tags:
        - Challenges
      security:
        - None: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "### Authorization Code Flow\n\
        \ The authorization code flow allows your users to **login with lishogi**.\n\
        \ - [NodeJS example](https://github.com/lishogi-org/api/tree/master/example/oauth-authorization-code)\n\
        \ - [Create a Lishogi OAuth app](https://lishogi.org/account/oauth/app)\n\
        \ - [About authorization code flow](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2#grant-type-authorization-code)\n\
        \n### Personal API Token\n\
        \ Personal API tokens allow you to quickly interact with Lishogi OAuth API.\n\
        \ - `curl https://lishogi.org/api/account -H \"Authorization: Bearer <token>\"`\n\
        \ - [NodeJS example](https://github.com/lishogi-org/api/tree/master/example/oauth-personal-token)\n\
        \ - [Generate a personal API token](https://lishogi.org/account/oauth/token)"
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.lishogi.org/oauth/authorize
          tokenUrl: https://oauth.lishogi.org/oauth
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "tournament:write": Create tournaments
            "puzzle:read": Read puzzle activity
            "team:write": Join, leave, and manage teams
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
    SameOrigin:
      description: "CORS is supported on almost all endpoints, except those tagged `SameOrigin`."
      type: none
    None:
      description: "No authorization required.\n\
        \ For requests that don't need an authenticated user."
      type: none
